"""
ml_scorer.py — F1 XGBoost Transaction Scorer
=============================================
Trains (first run) or loads a persisted XGBoost binary classifier on the
synthetic dataset generated by data_generator.py.

Public API
----------
  get_scorer() -> MLScorer        # singleton accessor
  MLScorer.score(features) -> float   # 0.0–1.0 fraud probability
  MLScorer.predict_proba_batch(df) -> np.ndarray
"""

from __future__ import annotations

import logging
import os
import pickle
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

MODEL_PATH = Path(__file__).parent.parent / "data" / "xgb_model.pkl"
DATA_PATH  = Path(__file__).parent.parent / "data" / "transactions.csv"

# Feature columns consumed by the ML model (must match data_generator output)
FEATURE_COLS = [
    "amount_log",
    "is_new_device",
    "geo_mismatch",
    "velocity_count",
    "velocity_spike",
    "blacklisted_ip",
    "collect_request",
    "sim_change_velocity",
    "category_anomaly",
    "chargeback_rate",
]

_SCORER_SINGLETON: Optional["MLScorer"] = None


class MLScorer:
    """Thin wrapper around XGBoostClassifier; serialised to disk after training."""

    def __init__(self) -> None:
        self.model = None
        self.X_test: Optional[pd.DataFrame] = None
        self.y_test: Optional[pd.Series]    = None
        self._load_or_train()

    # ------------------------------------------------------------------
    def _load_or_train(self) -> None:
        if MODEL_PATH.exists():
            logger.info("[MLScorer] Loading persisted model from %s", MODEL_PATH)
            with open(MODEL_PATH, "rb") as fh:
                payload = pickle.load(fh)
            self.model  = payload["model"]
            self.X_test = payload.get("X_test")
            self.y_test = payload.get("y_test")
        else:
            self._train()

    def _train(self) -> None:
        from sklearn.model_selection import train_test_split
        from sklearn.preprocessing import StandardScaler

        # Lazy import to keep startup fast when model already exists
        try:
            from xgboost import XGBClassifier
        except ImportError as exc:
            raise RuntimeError("xgboost not installed — run: pip install xgboost") from exc

        if not DATA_PATH.exists():
            logger.info("[MLScorer] No dataset found — running data_generator first…")
            from data_generator import generate_and_save  # type: ignore
            generate_and_save()

        logger.info("[MLScorer] Training XGBoost on %s …", DATA_PATH)
        df = pd.read_csv(DATA_PATH)

        # Ensure all feature columns exist; fill missing with 0
        for col in FEATURE_COLS:
            if col not in df.columns:
                df[col] = 0.0

        X = df[FEATURE_COLS].fillna(0.0)
        y = df["is_fraud"]

        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.20, random_state=42, stratify=y
        )

        model = XGBClassifier(
            n_estimators=200,
            max_depth=5,
            learning_rate=0.08,
            subsample=0.8,
            colsample_bytree=0.8,
            eval_metric="logloss",
            random_state=42,
            n_jobs=-1,
        )
        model.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=False)

        self.model  = model
        self.X_test = X_test
        self.y_test = y_test

        MODEL_PATH.parent.mkdir(exist_ok=True)
        with open(MODEL_PATH, "wb") as fh:
            pickle.dump({"model": model, "X_test": X_test, "y_test": y_test}, fh)
        logger.info("[MLScorer] Model saved to %s", MODEL_PATH)

        # Log test-set metrics
        self._log_metrics()

    def _log_metrics(self) -> None:
        from sklearn.metrics import classification_report
        if self.X_test is None or self.y_test is None:
            return
        y_pred = self.model.predict(self.X_test)
        report = classification_report(self.y_test, y_pred, digits=3)
        logger.info("[MLScorer] Test-set performance:\n%s", report)

    # ------------------------------------------------------------------
    def score(self, features: dict) -> float:
        """Return fraud probability [0.0, 1.0] for a single transaction."""
        row = {col: features.get(col, 0.0) for col in FEATURE_COLS}
        df  = pd.DataFrame([row])
        prob: float = float(self.model.predict_proba(df)[0, 1])
        return prob

    def predict_proba_batch(self, df: pd.DataFrame) -> np.ndarray:
        """Score a DataFrame; returns array of fraud probabilities."""
        for col in FEATURE_COLS:
            if col not in df.columns:
                df[col] = 0.0
        return self.model.predict_proba(df[FEATURE_COLS].fillna(0.0))[:, 1]

    def precision_recall_at_threshold(
        self,
        threshold: float,
        fp_cost: float = 500.0,
        tp_benefit: float = 12500.0,
        fn_cost: float = 12500.0,
    ) -> dict:
        """Compute real precision/recall & business cost impact on held-out test set at given threshold."""
        if self.X_test is None or self.y_test is None:
            return {
                "precision": 0.0, "recall": 0.0,
                "tp": 0, "fp": 0, "fn": 0, "tn": 0,
                "fp_cost": 0.0, "fraud_prevented": 0.0, "fn_cost": 0.0, "net_impact": 0.0
            }
        from sklearn.metrics import confusion_matrix, precision_score, recall_score

        probs = self.model.predict_proba(self.X_test)[:, 1]
        preds = (probs >= threshold / 100.0).astype(int)
        
        precision = float(precision_score(self.y_test, preds, zero_division=0))
        recall    = float(recall_score(self.y_test, preds, zero_division=0))
        
        tn, fp, fn, tp = confusion_matrix(self.y_test, preds).ravel()

        est_fp_cost = float(fp * fp_cost)
        est_fraud_prevented = float(tp * tp_benefit)
        est_fn_cost = float(fn * fn_cost)
        net_impact = est_fraud_prevented - est_fp_cost - est_fn_cost

        return {
            "precision": round(precision * 100, 1),
            "recall": round(recall * 100, 1),
            "tp": int(tp),
            "fp": int(fp),
            "fn": int(fn),
            "tn": int(tn),
            "fp_cost": round(est_fp_cost, 2),
            "fraud_prevented": round(est_fraud_prevented, 2),
            "fn_cost": round(est_fn_cost, 2),
            "net_impact": round(net_impact, 2),
        }


def get_scorer() -> MLScorer:
    """Return (or lazily create) the process-wide MLScorer singleton."""
    global _SCORER_SINGLETON
    if _SCORER_SINGLETON is None:
        _SCORER_SINGLETON = MLScorer()
    return _SCORER_SINGLETON
